<?xml version="1.0" encoding="UTF-8"?><testrun name="UT2004TournamentTest01_UT2004CaptureTheFlag" project="UT2004-tournament_NEW" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="cz.cuni.amis.pogamut.ut2004.tournament.capturetheflag.UT2004TournamentTest01_UT2004CaptureTheFlag" time="0.154">
    <testcase name="test01" classname="cz.cuni.amis.pogamut.ut2004.tournament.capturetheflag.UT2004TournamentTest01_UT2004CaptureTheFlag" time="0.154">
      <error>PogamutException[cz.cuni.amis.pogamut.ut2004.tournament.capturetheflag.UT2004CaptureTheFlagConfig@5b14: cz.cuni.amis.pogamut.ut2004.tournament.capturetheflag.UT2004CaptureTheFlagConfig@5b14 validation error!&#13;
UccWrapper.UnrealHome does not point to directory, used path: D:\Games\UT2004-Devel]&#13;
	at cz.cuni.amis.pogamut.ut2004.tournament.match.UT2004MatchConfig.validate(UT2004MatchConfig.java:496)&#13;
	at cz.cuni.amis.pogamut.ut2004.tournament.match.UT2004Match.validate(UT2004Match.java:281)&#13;
	at cz.cuni.amis.pogamut.ut2004.tournament.capturetheflag.UT2004CaptureTheFlag.execute(UT2004CaptureTheFlag.java:561)&#13;
	at cz.cuni.amis.pogamut.ut2004.tournament.capturetheflag.UT2004TournamentTest01_UT2004CaptureTheFlag.test01(UT2004TournamentTest01_UT2004CaptureTheFlag.java:97)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
